[package]
name = "flacman"
version = "0.1.0"
edition = "2024"

[dependencies]
audiotags = "0.5.0"
clap = { version = "4.5.48", features = ["derive"] }
heapless = "0.9.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.7"
